-- 口罩訂購助手 v2.3.0：帳號救援、安全紀錄與臨時密碼流程
-- 請先完成 v2.2.0 與 v2.2.2，再於 Supabase SQL Editor 執行本檔一次。

create table if not exists public.mask_security_events (
  id bigint generated by default as identity primary key,
  event_type text not null,
  actor_user_id uuid references auth.users(id) on delete set null,
  target_user_id uuid references auth.users(id) on delete set null,
  detail text not null default '',
  created_at timestamptz not null default now()
);

-- 公開救援要求只保存不可逆雜湊，用於 15 分鐘內最多三次的頻率限制。
create table if not exists public.mask_recovery_requests (
  id bigint generated by default as identity primary key,
  identifier_hash text not null,
  requested_at timestamptz not null default now()
);
create index if not exists mask_recovery_requests_limit_idx
  on public.mask_recovery_requests(identifier_hash,requested_at desc);
alter table public.mask_recovery_requests enable row level security;
revoke all on public.mask_recovery_requests from anon,authenticated;

create index if not exists mask_security_events_created_idx
  on public.mask_security_events(created_at desc);
create index if not exists mask_security_events_target_idx
  on public.mask_security_events(target_user_id,created_at desc);

alter table public.mask_security_events enable row level security;
revoke all on public.mask_security_events from anon,authenticated;

create or replace function public.mask_list_security_events()
returns table(
  id bigint,event_type text,actor_user_id uuid,target_user_id uuid,
  detail text,created_at timestamptz
)
language sql security definer set search_path=public as $$
  select e.id,e.event_type,e.actor_user_id,e.target_user_id,e.detail,e.created_at
  from public.mask_security_events e
  join public.mask_app_members me on me.user_id=auth.uid() and me.approved
  where me.role='admin' or e.target_user_id=auth.uid() or e.actor_user_id=auth.uid()
  order by e.created_at desc
  limit 100;
$$;

revoke execute on function public.mask_list_security_events() from public,anon;
grant execute on function public.mask_list_security_events() to authenticated;

-- 修改密碼時同步留下安全紀錄，並解除「必須修改密碼」。
create or replace function public.mask_mark_password_changed()
returns void language plpgsql security definer set search_path=public as $$
begin
  if auth.uid() is null then raise exception 'NOT_AUTHENTICATED'; end if;
  update public.mask_app_members
  set must_change_password=false,updated_at=now()
  where user_id=auth.uid();
  insert into public.mask_security_events(event_type,actor_user_id,target_user_id,detail)
  values('password_changed',auth.uid(),auth.uid(),'使用者已設定自己的密碼');
end; $$;

revoke execute on function public.mask_mark_password_changed() from public,anon;
grant execute on function public.mask_mark_password_changed() to authenticated;
