-- 口罩訂購助手 v3.0.0：公開買家訂購、訂購活動與後台彙整
-- 請先完成 v2.3.0，再於 Supabase SQL Editor 執行本檔一次。

create table if not exists public.mask_order_campaigns (
  id uuid primary key default gen_random_uuid(),
  name text not null,
  slug text not null unique check (slug ~ '^[a-z0-9][a-z0-9-]{2,47}$'),
  description text not null default '',
  opens_at timestamptz,
  closes_at timestamptz,
  active boolean not null default false,
  allow_edit boolean not null default true,
  fulfillment_options jsonb not null default '["面交","宅配"]'::jsonb,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mask_buyer_orders (
  id uuid primary key default gen_random_uuid(),
  campaign_id uuid not null references public.mask_order_campaigns(id) on delete restrict,
  order_no text not null unique,
  edit_token_hash text not null,
  customer jsonb not null,
  items jsonb not null,
  total_qty integer not null check(total_qty > 0),
  subtotal numeric(12,2) not null default 0,
  shipping numeric(12,2) not null default 0,
  tax numeric(12,2) not null default 0,
  total numeric(12,2) not null default 0,
  status text not null default 'pending'
    check(status in ('pending','confirmed','contact','aggregated','cancelled','completed')),
  buyer_updated_at timestamptz,
  reviewed_by uuid references auth.users(id) on delete set null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.mask_public_order_attempts (
  id bigint generated by default as identity primary key,
  source_hash text not null,
  attempted_at timestamptz not null default now()
);

create index if not exists mask_campaign_active_idx on public.mask_order_campaigns(active,closes_at);
create index if not exists mask_buyer_orders_campaign_idx on public.mask_buyer_orders(campaign_id,created_at desc);
create index if not exists mask_buyer_orders_status_idx on public.mask_buyer_orders(status,created_at desc);
create index if not exists mask_public_attempt_limit_idx on public.mask_public_order_attempts(source_hash,attempted_at desc);

alter table public.mask_order_campaigns enable row level security;
alter table public.mask_buyer_orders enable row level security;
alter table public.mask_public_order_attempts enable row level security;
revoke all on public.mask_order_campaigns from anon,authenticated;
revoke all on public.mask_buyer_orders from anon,authenticated;
revoke all on public.mask_public_order_attempts from anon,authenticated;

create or replace function public.mask_admin_list_campaigns()
returns setof public.mask_order_campaigns
language sql security definer set search_path=public as $$
  select c.* from public.mask_order_campaigns c
  where public.mask_has_permission('record_view')
  order by c.created_at desc;
$$;

create or replace function public.mask_admin_save_campaign(
  p_id uuid,p_name text,p_slug text,p_description text,p_opens_at timestamptz,
  p_closes_at timestamptz,p_active boolean,p_allow_edit boolean,p_fulfillment_options jsonb
) returns uuid language plpgsql security definer set search_path=public as $$
declare v_id uuid;
begin
  if not public.mask_has_permission('settings_manage') then raise exception 'PERMISSION_DENIED'; end if;
  if trim(coalesce(p_name,''))='' then raise exception 'CAMPAIGN_NAME_REQUIRED'; end if;
  if p_slug !~ '^[a-z0-9][a-z0-9-]{2,47}$' then raise exception 'INVALID_SLUG'; end if;
  if p_closes_at is not null and p_opens_at is not null and p_closes_at<=p_opens_at then raise exception 'INVALID_PERIOD'; end if;
  if p_id is null then
    insert into public.mask_order_campaigns(name,slug,description,opens_at,closes_at,active,allow_edit,fulfillment_options,created_by)
    values(trim(p_name),p_slug,coalesce(p_description,''),p_opens_at,p_closes_at,p_active,p_allow_edit,coalesce(p_fulfillment_options,'[]'::jsonb),auth.uid())
    returning id into v_id;
  else
    update public.mask_order_campaigns set name=trim(p_name),slug=p_slug,description=coalesce(p_description,''),
      opens_at=p_opens_at,closes_at=p_closes_at,active=p_active,allow_edit=p_allow_edit,
      fulfillment_options=coalesce(p_fulfillment_options,'[]'::jsonb),updated_at=now()
    where id=p_id returning id into v_id;
  end if;
  return v_id;
end; $$;

create or replace function public.mask_admin_list_buyer_orders(p_campaign_id uuid default null)
returns table(
  id uuid,campaign_id uuid,campaign_name text,order_no text,customer jsonb,items jsonb,
  total_qty integer,subtotal numeric,shipping numeric,tax numeric,total numeric,status text,
  buyer_updated_at timestamptz,created_at timestamptz,updated_at timestamptz
) language sql security definer set search_path=public as $$
  select o.id,o.campaign_id,c.name,o.order_no,o.customer,o.items,o.total_qty,o.subtotal,o.shipping,o.tax,o.total,o.status,
    o.buyer_updated_at,o.created_at,o.updated_at
  from public.mask_buyer_orders o join public.mask_order_campaigns c on c.id=o.campaign_id
  where public.mask_has_permission('record_view') and (p_campaign_id is null or o.campaign_id=p_campaign_id)
  order by o.created_at desc;
$$;

create or replace function public.mask_admin_update_buyer_order(p_order_id uuid,p_status text,p_customer jsonb default null)
returns void language plpgsql security definer set search_path=public as $$
begin
  if not public.mask_has_permission('record_apply') then raise exception 'PERMISSION_DENIED'; end if;
  if p_status not in ('pending','confirmed','contact','aggregated','cancelled','completed') then raise exception 'INVALID_STATUS'; end if;
  update public.mask_buyer_orders set status=p_status,customer=coalesce(p_customer,customer),reviewed_by=auth.uid(),updated_at=now()
  where id=p_order_id;
end; $$;

revoke execute on function public.mask_admin_list_campaigns() from public,anon;
revoke execute on function public.mask_admin_save_campaign(uuid,text,text,text,timestamptz,timestamptz,boolean,boolean,jsonb) from public,anon;
revoke execute on function public.mask_admin_list_buyer_orders(uuid) from public,anon;
revoke execute on function public.mask_admin_update_buyer_order(uuid,text,jsonb) from public,anon;
grant execute on function public.mask_admin_list_campaigns() to authenticated;
grant execute on function public.mask_admin_save_campaign(uuid,text,text,text,timestamptz,timestamptz,boolean,boolean,jsonb) to authenticated;
grant execute on function public.mask_admin_list_buyer_orders(uuid) to authenticated;
grant execute on function public.mask_admin_update_buyer_order(uuid,text,jsonb) to authenticated;
